#!/bin/bash

apt-get install -y aide aide-common

aideinit

cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db

update-aide.conf

cp /etc/aide/aide.conf /etc/aide/aide.conf.old

cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
