#!/bin/bash

apt-get install -y sysstat

sysstat_file=/etc/default/sysstat
sed -i 's|^.*ENABLED.*$|ENABLED="true"|g' "$sysstat_file"

apt-get install -y auditd
apt-get install -y aide aide-common
apt-get install -y acct

cp audit.rules /etc/audit/rules.d/audit.rules

aideinit

cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db

update-aide.conf

cp /etc/aide/aide.conf /etc/aide/aide.conf.old

cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
